import pandas as pd

sample_data = [
    ("INR 500.00 credited to your account", 0),
    ("INR 1000 debited from your account for UPI payment", 1),
    ("Your account XX1234 has been credited with Rs.750.00", 0),
    ("Payment of Rs.250.00 sent to user@upi", 1),
    ("Rs.1500 received from rajesh@oksbi via UPI", 0),
    ("₹200.00 sent to amazon@okicici using BHIM UPI", 1),
    ("Credited ₹1200 from flipkart@ybl", 0),
    ("Debited ₹999 for payment to zomato@upi", 1),
    ("Rs.349 received from phonepe@ybl", 0),
    ("Paid ₹599 to swiggy@axisbank via UPI Ref no 98234", 1),
    ("₹1099 credited to your account via NEFT from abc@okhdfcbank", 0),
    ("₹450 sent to rent@upi from your account", 1),
    ("Received ₹3000 from salary@axisbank via UPI", 0),
    ("Rs.129 transferred to airtel@upi", 1),
    ("Rs.90.00 credited from cashback@paytm", 0),
    ("Payment of Rs.150 sent to movie@okhdfcbank", 1),
    ("Account XX8921 has been credited with ₹1800.00 from work@ybl", 0),
    ("₹749 paid to net@upi from your a/c", 1),
    ("Received ₹2100 from employer@okaxis via UPI", 0),
    ("Sent ₹230 to recharge@upi through Google Pay", 1),
    ("UPI: ₹400 received from friend@ybl", 0),
    ("Paid ₹800 to food@okaxis via PhonePe", 1),
    ("₹1050 credited via UPI from upi@flipkart", 0),
    ("UPI payment of ₹300 done to abc@okhdfc", 1),
    ("Your A/c has been credited with ₹950.00 by paytm@ybl", 0),
    ("₹425.50 sent to utility@oksbi using BHIM", 1),
    ("Received ₹1350 from savings@okaxisbank", 0),
    ("Payment ₹999 sent to gift@ybl", 1),
    ("Rs.2500 deposited via UPI from rewards@upi", 0),
    ("Sent ₹410 to fuel@upi Ref: BHIM1234", 1),
    ("Rs.600.00 credited from bonus@axisbank", 0),
    ("Payment of ₹1450 to sharma@okhdfcbank has been completed", 1),
    ("Rs.899 received from freelance@ybl", 0),
    ("You paid ₹720 to netflix@upi", 1),
    ("₹350 received from cashback@okaxisbank", 0),
    ("Rs.200.00 debited to pay electricity@upi", 1),
    ("Rs.1200 added from business@upi to your account", 0),
    ("Paid ₹500 to doctor@oksbi via PhonePe", 1),
    ("Credited ₹1000 from rewards@ybl", 0),
    ("₹650 transferred to hostel@upi", 1),
    ("₹250.00 received from brother@oksbi", 0),
    ("₹870.00 paid to amazon@okaxis Ref: UPI928377", 1),
    ("Credited ₹2000 from taxrefund@upi", 0),
    ("Paid ₹300 to upsc@okhdfc", 1),
    ("Received ₹1999 from cashback@paytm", 0),
    ("Debited ₹450 to rent@oksbi", 1),
    ("₹720 credited from vendor@upi", 0),
    ("Sent ₹510 to travel@okhdfcbank", 1),
    ("₹400 received from friend@okicici", 0),
    ("Paid ₹799 to delivery@upi Ref: 893245", 1),
]

df = pd.DataFrame(sample_data, columns=['text', 'label'])

df.to_csv('data/training_data.csv', index=False)
print("Sample training data created!") 